"""empty message

Revision ID: 1a00e7f44f0a
Revises: 906418b3e12d
Create Date: 2025-04-30 15:40:01.400128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a00e7f44f0a'
down_revision = '906418b3e12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('red_pixels', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('green_pixels', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_pixels', sa.Integer(), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('upload_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.alter_column('upload_time',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('blue_pixels')
        batch_op.drop_column('green_pixels')
        batch_op.drop_column('red_pixels')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
