"""empty message

Revision ID: 770df91b3a9b
Revises: 3c9760cd313c
Create Date: 2025-05-06 08:35:47.033423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770df91b3a9b'
down_revision = '3c9760cd313c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('restaurant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('street_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant', sa.INTEGER(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('review_text', sa.VARCHAR(length=500), nullable=True),
    sa.Column('review_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
