"""Nueva migracion con ImageUpload

Revision ID: 906418b3e12d
Revises: d0c7b8e4b57c
Create Date: 2025-04-28 09:58:05.563824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906418b3e12d'
down_revision = 'd0c7b8e4b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('upload_time', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_upload')
    # ### end Alembic commands ###
